### ISSUE TITLE
I can't play music D=

### ISSUE THREAD

**Issue by KPCGKG** [Cazzar/JukeboxReloaded#10]
Whenever I click the play button it won't play at all

**Comment by cazzar** [comment]
Firstly, Commenting here, [On the forums](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1288485-cazzars-mods-jukebox-reloaded-jukebox-fix?page=9#c170) and [On CurseForge](http://minecraft.curseforge.com/mc-mods/77021-jukebox-reloaded?comment=3) within 13 hours, isn't the best to do, and as well as this, since you have provided me with little to no information, I must request logs, since, it might actually be some other issue which could be detailed in the forge log files.

**Comment by Cazzar** [comment]
Due to lack of response, I am closing this as invalid.
